### ISSUE TITLE
Can't access ESP8266 via browser on local network even though it's connected to router

### ISSUE THREAD

**Issue by chrisp79** [mdhiggins/ESP8266-HTTP-IR-Blaster#199]
Hi. I'm pretty much a newbie when it comes to all this so apologies if I'm missing something really obvious.

With much research, self-teaching, trial and error I've managed to get as far as 6:50 in your brilliant YouTube video (https://www.youtube.com/watch?v=JysKXOdrOlM&feature=youtu.be) but no matter what I try (and I've tried everything I can think of / see mentioned online) I cannot access my ESP board.

I've found my ESP board's MAC address and I can see that it's connecting to my router. I've tried accessing the board by typing **irblaster.local:80** into my browser with no success. I do realise this is dependent on having MDNS and I'm not really sure if I do or don't to be honest, so have been focussing on entering it's IP address e.g. 192.168.0.99 which, from what I can see, should be guaranteed to work. However, no success with that either. In all cases I just get a "Page cannot be reached" page - that's using IE and Chrome. I have tried setting it up with many different IP addresses and can see on my router's "Connected Devices" page that it is connecting successfully and assigning it the IP addresses I specify each time.

My issue seems to be very similar to **Config file and WiFi Manager #110 ** - albeit his had been working previously then stopped - I've never got mine working.

Is as if the device is connecting but it isn't starting it's web interface. I bought two boards and both act the same way, so I don't think it's down to a faulty board.

Any ideas / advice would be gratefully received - I'd love to get past 06:50 in your video!!

Thanks,
Chris

**Comment by mdhiggins** [comment]
If you could post your serial output during boot that would be appreciated

Additionally, please post the local IP information of the device on your network you're trying to use to access the device (your computer)

If on windows, you can get this by opening up command prompt and typing ipconfig

If you can post this information I can try to further help

**Comment by chrisp79** [comment]
Hi, thanks for getting back to me so quickly.

I abandoned the first of my two boards after a few hours at the weekend when I couldn't get it working and moved onto my second board. When I couldn't get that working either, I decided it wasn't a board issue and started playing around with library versions, etc - trying every version and combinations. I did all that really intense testing with the 2nd board and it was after this that I created this thread.

For some reason, I thought just now, I'd give the original board a try seeing as I gave up on that one quite quickly - just in case. I didn't expect anything different but, that one is now working!!

I can only conclude that I inadvertently stumbled upon the correct combination of library versions, etc whilst testing with my 2nd board, but that that board is somehow bust. How annoying!

I've now been able to learn a code, create an Alexa device, associate the code with that device, get Alexa to discover it and I can see the red LED on the board flash when I ask Alexa to control it - so I've clearly managed to get the port forwarding sorted too. Brilliant!

The signal isn't actually getting through to my A/C unit though for whatever reason, so I need to 'debug' that now. But it's a huge step forward. Hopefully I'll be able to figure that out myself in the near future, but I know now where to come if I get stuck.

Thanks again
Chris

**Comment by mdhiggins** [comment]
AC units can be particularly challenging as their codes are often very long and not always going to work

Make sure you’re not sending an ‘UNKNOWN’ code too, if the code is read as unknown you have to send the RAW format

**Comment by chrisp79** [comment]
Awesome, thanks for the tip. Maybe I'll try getting it working with a TV first then before moving on to my A/C unit

**Comment by mdhiggins** [comment]
I would definitely advise that

#187 has a post I made going through the specifics of which latest library has been tested and should be working if you want to check it against your own setup

**Comment by chrisp79** [comment]
Thanks again. I will try and compare that list and my own tomorrow and see if I can make any improvements. All seems pretty stable though how I have it now ;o)

Seem to be able to receive codes and I think I understand how I transmit them now via URL. Can't get my TV to respond though. Will have another go at the weekend.

Thanks again

**Comment by SirJMD** [comment]
I seem to have the same issue. My D1 mini becomes unresponsive mere seconds after booting. In the first couple of seconds I can access the web interface and ping the D1 mini, but it dies within 5 seconds. After that, no web or ping.

```
*WM: Connection result:
*WM: 3
*WM: IP Address:
*WM: 192.168.1.105
WiFi connected! User chose hostname 'Blaster' passcode '1234' and port '80'
WiFi configuration complete
Local IP: 192.168.1.105
URL to send commands: http://Blaster.local:80
ArduinoOTA started
MDNS http service added. Hostname is set to Blaster.local:80
HTTP Server started on port 80
Turning off the LED to save power.
Error retrieving external IP
HTTP Code: -1
connection refused
External IP address request took 5023 ms
Ready to send and receive IR signals
```

Only change I've made is to disable external IP check.

**Comment by chrisp79** [comment]
Hi SirJMD. That's slightly different to my issue - I couldn't access the web interface even for those first few seconds when the board was 'pingable'. I'm still not convinced the 2nd board I spent most of my time trying to get working wasn't physically bust. The versions of the software, libraries, boards, etc, that I eventually found worked on my 1st board are as follows;

Arduino			v1.8.5
Board: 			NodeMCU 1.0 (ESP-12E Module)
Flash size:		       4M (1M SPIFFS)
IwIP Variant:		v1.4 Prebuilt
CPU frequency:	80 MHz
Upload speed:		115200
Programmer:		AVRISP mkll

Board Manager
esp8266			v2.4.0

Library Manager
ESP8266WebServer 	v1.0.0
ESP8266WiFi 		v1.0.0
ArduinoJson 		v5.13.2	
WiFiManager 		v0.12.0
EasyNTPClient 		v1.0.0
IRremoteESP8266		v2.4.0

**Comment by SirJMD** [comment]
I don't have "IwIP Variant: v1.4 Prebuilt", I have "Higher bandwidth" and "Compile from source". Currently using "Higher bandwidth".

Gonna try:
ESP8266 2.4.0 (currently 2.4.1)
ArduinoJson v5.13.2 (currently v5.13.1)
EasyNTPClient v1.0.0 (currently v.1.1.0)
IRremoteESP8266 v2.4.0 (currently v2.4.3)

**Comment by SirJMD** [comment]
Now it's completely unresponsive.. 2 steps back :dagger: 

EDIT: With ESP8266 back to 2.4.1 the board become responsive again, but dies after a few seconds.

**Comment by war6000** [comment]
I’m getting the same error as the previous person. Any solutions or at least knowledge of what might be the next thing to diagnose

**Comment by SirJMD** [comment]
I'm stuck. No matter what I try it dies after just a few seconds.

**Comment by mdhiggins** [comment]
@SirJMD If you don't see lwIP Variant v1.4 Prebuilt its because you're using the wrong version of the Arduino ESP8266 Core (needs to be 2.4.0, 2.4.1 DOES NOT work) and possibly you have the wrong board selected from your board manager. Until you get the right combination including v1.4 Prebuilt the memory leak will cause freezing and it will not work

See #187 for all the specifics

**Comment by SirJMD** [comment]
@mdhiggins I noticed that after downgrading. However, 2.4.0 just results in the ESP8266 being completely unresponsive. With 2.4.1 the AP mode works fine and I can setup wifi connection and everything, but as soon as it reboots its only alive for a few seconds. 2.4.0 doesn't even get to the AP mode.

I'm using the "Generic ESP8266" in the board manager, which has worked so far for everything else.

**Comment by mdhiggins** [comment]
What does the serial output say?

**Comment by SirJMD** [comment]
Nothing at all. No communication at all.

If you have any ideas on how to zero in on the issue, I'd be happy to test it and report back.

**Comment by mdhiggins** [comment]
That doesn't make any sense, you need to reflash or recheck your Arduino libraries and potentially reinstall 2.4.0 because something is broken then. Try deleting your 2.4.0 install and redownloading

**Comment by SirJMD** [comment]
I'll give that a shot tonight.

**Comment by SirJMD** [comment]
Just tested deleting the esp8266 board folder and reinstalling 2.4.0. The board is yet again completely unresponsive. Nothing on the serial monitor at all.

With 2.4.1 I'm getting this:
```
ESP8266 IR Controller
Config pin GPIO10 set to: 1
failed to mount FS
*WM: Adding parameter
*WM: hostname
*WM: Adding parameter
*WM: passcode
*WM: Adding parameter
*WM: port_str
*WM: Adding parameter
*WM: user_id
Using Static IP
*WM: 
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Custom STA IP/GW/Subnet
*WM: 192.168.1.105
*WM: Using last saved values, should be faster
*WM: Connection result: 
*WM: 0
*WM: SET AP STA
Entered config mode
192.168.4.1
IR Controller Configuration
*WM: 
*WM: Configuring access point... 
*WM: IR Controller Configuration
*WM: AP IP address: 
*WM: 192.168.4.1
*WM: HTTP server started
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Handle root
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Scan done
*WM: TP-Link_701F
*WM: -89
*WM: HP-Print-90-Photosmart 6520
*WM: -95
*WM: Sent config page
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: Request redirected to captive portal
*WM: WiFi save
*WM: Parameter
*WM: hostname
*WM: Blaster
*WM: Parameter
*WM: passcode
*WM: 1234
*WM: Parameter
*WM: port_str
*WM: 80
*WM: Parameter
*WM: user_id
*WM: Testuser
*WM: static ip
*WM: 192.168.1.105
*WM: static gateway
*WM: 192.168.1.1
*WM: static netmask
*WM: 255.255.255.0
*WM: Sent wifi save page
*WM: Connecting to new AP
*WM: Connecting as wifi client...
*WM: Custom STA IP/GW/Subnet
*WM: 192.168.1.105
*WM: Already connected. Bailing out.
Should save config
WiFi connected! User chose hostname 'Blaster' passcode '1234' and port '80'
 config...
failed to open config file for writing
{"hostname":"Blaster","passcode":"1234","port_str":"80","user_id":"Testuser","ip":"192.168.1.105","gw":"192.168.1.1","sn":"255.255.255.0"}
Writing config file
Config written successfully
WiFi configuration complete
Local IP: 192.168.1.105
URL to send commands: http://Blaster.local:80
HTTP Server started on port 80
Warning, user_id appears to be in the wrong format, security check will most likely fail. Should start with amzn1.account.***
EPOCH time obtained for security checks
Ready to send and receive IR signals
Turning off the LED to save power.
```

Right after it turns off the LED, it stops responding.

**Comment by mdhiggins** [comment]
The loss of response is expected with 2.4.1 - its a known bug due to a memory leak in changes made to the WiFi libraries. There's been countless people opening issues about this and a persistent one I opened myself. Unfortunately it is not yet fixed but its out of my hands to fix until they update the ESP8266 Arduino Core

Now why 2.4.0 isn't working is very strange and to get no response at all is even more strange but I can assure you that the entire project was developed with 2.4.0 and does work so it must be something unique on your end

What board do you have set?
What are all your compile and upload options? (Frequency, SPIFFS, baud etc)
What hardware are you using?

**Comment by SirJMD** [comment]
I'm using a Wemos D1 mini clone, with a ESP8266MOD. It's been working fine in other projects, but for some reason not this time.

My settings follow the ones recommended for Tasmota:
https://github.com/arendst/arendst.github.io/raw/master/media/arduinoide2b.png

What are the other hardware specs are you asking for?

**Comment by mdhiggins** [comment]
Try using NodeMCU 1.0 (ESP-12E Module) and 3M SPIFFS

**Comment by SirJMD** [comment]
That seems to work! It hasn't crashed yet and the web ui seems to work (it won't read IR codes yet, probably a wiring error on my part).

Interesting.. what's your reasoning behind suggesting that solution?

**Comment by mdhiggins** [comment]
Most of the libraries are developed against the NodeMCU board generic so you get better compatibility

And SPIFFS is the filesystem the devices saves settings against, so no SPIFFS causes problems

**Comment by SirJMD** [comment]
Interesting. I will do some more testing tonight. With the "Generic ESP8266" chosen I had tried many different settings for flash size, and tested it with the ESP8266 example that tests the flash configuration.  Based on that a setting of 4M with 1M SPIFF resulted in config OK.

For this project it made no difference what I chose.

**Comment by mdhiggins** [comment]
I've found that the NodeMCU 1.0 works much better than the "Generic ESP8266"
